__all__ = ["IdealMHDA",
           "IdealMHDB",
           "IdealMHDBussacA",
           "IdealMHDBussacB",
           "IdealMHD_cylA",
           "IdealMHD_cylB",
           "IdealMHDEulerA",
           "IdealMHDEulerB",
           "IdealMHDFlowEulerA",
           "IdealMHDFlowEulerB",
           "IdealMHDFlowBussacA",
           "IdealMHDFlowBussacB",
           "IdealMHDperpA",
           "IdealMHDperpB"
           ]
